### ISSUE TITLE
Finish v1.0 ui-components

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-components#10]
- [x] Finish “Questions and options” component
- [x] Finish “vote flow” component: vote, confirm screen, submit screen, success/error screen
- [x] #18
- [x] #17
- [x] Add “You already voted + voteProof”
- [x] #19
- [x] #8
- [x] https://github.com/vocdoni/ui-components/pull/14
	- [x] Data components (title, description, etc)
	- [x] hooks with account actions (like updating metadata)

Review final status and next steps.

**Comment by elboletaire** [comment]
Everything's done from this list, but I'd wait until some of these components are fully used and customized in the scaffold project.

**Comment by jpaulet** [comment]
We can close this, and resume it on September, with the launch at the same moment of UI-Components + SDK v1.0.
