### ISSUE TITLE
UI-Components: Documentation

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-components#11]
Document and publish the docs to Dev Portal

- [x] Documentation
     - [x] Add the current documentation on top of the repo readme 
- [x] Add a list of available components and how to use it (if possible, a visual example of the component)
     - [x] Decide how to order them, by component? by "area"?  
- [x] Add the docs to the Dev Portal (own section)

**Comment by elboletaire** [comment]
You have the components documentation in their folder btw: https://github.com/vocdoni/ui-components/tree/main/packages/components

**Comment by selankon** [comment]
Closed by #62
