### ISSUE TITLE
fallbackSrc not working 

### ISSUE THREAD

**Issue by selankon** [vocdoni/ui-components#56]
Tested on `OrganizationAvatar` and `OrganizationHeader`. 

Trying to give a `fallbackSrc` is not showing nothing. Tested code:

```tsx
const Test = () => {
    return <>
        <ChakraProvider theme={extendTheme(theme)} resetCSS={false}>
            <ClientProvider env='stg'>
                <OrganizationProvider id='f752b527e2aba395d1ba4c0de9c147b763dda1f4'>
                    <OrganizationAvatar
                        fallbackSrc={'/img/logo-dark.png'}
                    />
                    <OrganizationName />
                    <OrganizationHeader
                        fallbackSrc={'img/logo-dark.png'}
                    />
                </OrganizationProvider>
            </ClientProvider>
        </ChakraProvider>
    </>
}
```

**Comment by elboletaire** [comment]
lmao actually you're using a chakra feature I didn't know it exist. Apparently chakra already provides two `fallback` props:

- `fallback` for setting a custom React fallback component
- `fallbackSrc` for setting a custom fallback image source

So I'll remove the custom `fallback` prop I did add, and fix the component so it works with chakra's defaults.
